<?php
/**
 * Activaction
 *
 * @package    DFW
 * @subpackage DFW
 * @since      0.0.11
 */

if( !class_exists( 'DFW_Activation' ) ) {
	class DFW_Activation {

		/**
		 * Activation
		 *
		 * @since      0.0.11
		 * @return     void
		 */
		public function install() {
			$this->add_options();
		} // end __construct

		/**
		 * Add Options
		 *
		 * @since      0.0.11
		 * @return     void
		 */
		public function add_options() {
			$optins = array(
				// Archive Title
				'options_dfw_archive_title_header_tag'                => 'header',
				'_options_dfw_archive_title_header_tag'               => 'field_562ed1001052d',
				'options_dfw_archive_title_header_id'                 => 'archive__id-%POSTID%',
				'_options_dfw_archive_title_header_id'                => 'field_562ed1a854c67',
				'options_dfw_archive_title_header_class'              => 'archive__header',
				'_options_dfw_archive_title_header_class'             => 'field_562ed1d354c68',
				'options_dfw_archive_title_header_attr'               => 'aria-labelledby="section-heading-archive" role="article"',
				'_options_dfw_archive_title_header_attr'              => 'field_562ed45fba658',
				'options_dfw_archive_title_heading_tag'               => 'h1',
				'_options_dfw_archive_title_heading_tag'              => 'field_562ed49cba659',
				'options_dfw_archive_title_heading_id'                => 'archive_heading',
				'_options_dfw_archive_title_heading_id'               => 'field_562ed4c6ba65a',
				'options_dfw_archive_title_heading_class'             => 'archive__heading',
				'_options_dfw_archive_title_heading_class'            => 'field_562ed4f6ba65b',
				'options_dfw_archive_title_heading_attr'              => '',
				'_options_dfw_archive_title_heading_attr'             => 'field_562ed517ba65c',
				'options_dfw_archive_title_archives_title'            => 'Archives:',
				'_options_dfw_archive_title_archives_title'           => 'field_562ed543ba65d',
				'options_dfw_archive_title_category_title'            => 'Category:',
				'_options_dfw_archive_title_category_title'           => 'field_562ed56dba65e',
				'options_dfw_archive_title_tag_title'                 => 'Tag:',
				'_options_dfw_archive_title_tag_title'                => 'field_562ed620ba65f',
				'options_dfw_archive_title_author_title'              => 'Author:',
				'_options_dfw_archive_title_author_title'             => 'field_562ed63dba660',
				'options_dfw_archive_title_author_display'            => 'username',
				'_options_dfw_archive_title_author_display'           => 'field_56378ee348933',
				'options_dfw_archive_title_year_title'                => 'Year:',
				'_options_dfw_archive_title_year_title'               => 'field_562ed6fc19dc8',
				'options_dfw_archive_title_year_format'               => 'Y',
				'_options_dfw_archive_title_year_format'              => 'field_562ed72919dc9',
				'options_dfw_archive_title_month_title'               => 'Month:',
				'_options_dfw_archive_title_month_title'              => 'field_562ed74a19dca',
				'options_dfw_archive_title_day_title'                 => 'Day:',
				'_options_dfw_archive_title_day_title'                => 'field_562ed79119dcc',
				'options_dfw_archive_title_day_format'                => 'F j, Y',
				'_options_dfw_archive_title_day_format'               => 'field_562ed7c119dcd',
				// Custom Excerpt
				'options_dfw_custom_excerpt_tag'                      => 'p',
				'_options_dfw_custom_excerpt_tag'                     => 'field_563776f78471a',
				'options_dfw_custom_excerpt_content'                  => '%CONTENT%',
				'_options_dfw_custom_excerpt_content'                 => 'field_562ed8ad20f6e',
				'options_dfw_custom_excerpt_length'                   => '10',
				'_options_dfw_custom_excerpt_length'                  => 'field_562ed8e320f6f',
				'options_dfw_custom_excerpt_has_ellipsis'             => '1',
				'_options_dfw_custom_excerpt_has_ellipsis'            => 'field_562ed90520f70',
				'options_dfw_custom_excerpt_ellipsis'                 => '...',
				'_options_dfw_custom_excerpt_ellipsis'                => 'field_562ed92b20f71',
				'options_dfw_custom_excerpt_type'                     => 'word',
				'_options_dfw_custom_excerpt_type'                    => 'field_56376d8c540be',
				'options_dfw_custom_excerpt_ellipsis_link'            => '1',
				'_options_dfw_custom_excerpt_ellipsis_link'           => 'field_562edf22c9f59',
				'options_dfw_custom_excerpt_ellipsis_link_id'         => '',
				'_options_dfw_custom_excerpt_ellipsis_link_id'        => 'field_562edffcc9f5a',
				'options_dfw_custom_excerpt_ellipsis_link_class'      => '',
				'_options_dfw_custom_excerpt_ellipsis_link_class'     => 'field_562ee0ccc9f5b',
				'options_dfw_custom_excerpt_ellipsis_link_attr'       => 'rel="bookmark"',
				'_options_dfw_custom_excerpt_ellipsis_link_attr'      => 'field_562ee170c9f5c',
				'options_dfw_custom_excerpt_has_link'                 => '0',
				'_options_dfw_custom_excerpt_has_link'                => 'field_56376728254eb',
				'options_dfw_custom_excerpt_link_text'                => 'More',
				'_options_dfw_custom_excerpt_link_text'               => 'field_56376899254ec',
				'options_dfw_custom_excerpt_link_id'                  => 'ellipsis__link-id-%POSTID%',
				'_options_dfw_custom_excerpt_link_id'                 => 'field_563768eb254ed',
				'options_dfw_custom_excerpt_link_class'               => 'ellipsis__link-class',
				'_options_dfw_custom_excerpt_link_class'              => 'field_5637692f254ee',
				'options_dfw_custom_excerpt_link_attr'                => 'rel="bookmark"',
				'_options_dfw_custom_excerpt_link_attr'               => 'field_56376a0f254ef',
				'options_dfw_custom_excerpt_link_url'                 => '%PERMALINK%',
				'_options_dfw_custom_excerpt_link_url'                => 'field_56376a82254f0',
				'options_dfw_custom_excerpt_preserve'                 => '1',
				'_options_dfw_custom_excerpt_preserve'                => 'field_5637769784719',
				'options_dfw_custom_excerpt_ellipsis_id'              => 'ellipsis__id-%POSTID%',
				'_options_dfw_custom_excerpt_ellipsis_id'             => 'field_562edffcc9f5a',
				'options_dfw_custom_excerpt_ellipsis_class'           => 'ellipsis__class',
				'_options_dfw_custom_excerpt_ellipsis_class'          => 'field_562ee0ccc9f5b',
				'options_dfw_custom_excerpt_ellipsis_attr'            => 'rel="bookmark"',
				'_options_dfw_custom_excerpt_ellipsis_attr'           => 'field_562ee170c9f5c',
				// Display Author
				'options_dfw_display_author_wrapper'                  => 'span',
				'_options_dfw_display_author_wrapper'                 => 'field_563d28de07370',
				'options_dfw_display_author_wrapper_id'               => 'author__id-%AUTHORID%',
				'_options_dfw_display_author_wrapper_id'              => 'field_563d29e807371',
				'options_dfw_display_author_wrapper_class'            => 'author vcard',
				'_options_dfw_display_author_wrapper_class'           => 'field_563d2a6707372',
				'options_dfw_display_author_wrapper_attr'             => 'rel="author"',
				'_options_dfw_display_author_wrapper_attr'            => 'field_563d2b6f72c42',
				'options_dfw_display_author_author_text'              => 'By:',
				'_options_dfw_display_author_author_text'             => 'field_563d2c1772c43',
				'options_dfw_display_author_author_display'           => 'username',
				'_options_dfw_display_author_author_display'          => 'field_563d2cb672c44',
				'options_dfw_display_author_has_link'                 => '1',
				'_options_dfw_display_author_has_link'                => 'field_563d2dab72c46',
				'options_dfw_display_author_link_id'                  => 'author__link-id-%AUTHORID%',
				'_options_dfw_display_author_link_id'                 => 'field_563d2de572c47',
				'options_dfw_display_author_link_class'               => 'url fn n',
				'_options_dfw_display_author_link_class'              => 'field_563d2dec72c48',
				'options_dfw_display_author_link_attr'                => 'rel="bookmark"',
				'_options_dfw_display_author_link_attr'               => 'field_563d2df472c49',
				// List Terms
				'options_dfw_list_terms_wrapper'                      => 'div',
				'_options_dfw_list_terms_wrapper'                     => 'field_563e0a03e71a3',
				'options_dfw_list_terms_wrapper_id'                   => 'author__id-%AUTHORID%',
				'_options_dfw_list_terms_wrapper_id'                  => 'field_563e0a09e71a4',
				'options_dfw_list_terms_wrapper_class'                => '',
				'_options_dfw_list_terms_wrapper_class'               => 'field_563e0a0de71a5',
				'options_dfw_list_terms_wrapper_attr'                 => '',
				'_options_dfw_list_terms_wrapper_attr'                => 'field_563e0a14e71a6',
				'options_dfw_list_terms_text'                         => 'Listed In:',
				'_options_dfw_list_terms_text'                        => 'field_563f5f254d051',
				'options_dfw_list_terms_tax_type'                     => 'all',
				'_options_dfw_list_terms_tax_type'                    => 'field_563f54541bd56',
				'options_dfw_list_terms_term_class'                   => '',
				'_options_dfw_list_terms_term_class'                  => 'field_563f56221bd59',
				'options_dfw_list_terms_term_attr'                    => '',
				'_options_dfw_list_terms_term_attr'                   => 'field_563f56271bd5a',
				'options_dfw_list_terms_has_link'                     => '1',
				'_options_dfw_list_terms_has_link'                    => 'field_563f56f81bd5b',
				'options_dfw_list_terms_link_class'                   => '',
				'_options_dfw_list_terms_link_class'                  => 'field_563f57101bd5c',
				'options_dfw_list_terms_link_attr'                    => 'rel="bookmark"',
				'_options_dfw_list_terms_link_attr'                   => 'field_563f57161bd5d',
				'options_dfw_list_terms_list_style'                   => 'default',
				'_options_dfw_list_terms_list_style'                  => 'field_563f5bf41bd5e',
				'options_dfw_list_terms_list_delimer'                 => ',',
				'_options_dfw_list_terms_list_delimer'                => 'field_563f5c631bd5f',
				'options_dfw_list_terms_list_con'                     => 'and',
				'_options_dfw_list_terms_list_con'                    => 'field_563f5d0f1bd60',
				'options_dfw_list_terms_tax_list'                     => 'post_tag category',
				'_options_dfw_list_terms_tax_list'                    => 'field_563f54c51bd57',
				// Page Title
				'options_dfw_page_title_header_tag'                   => 'header',
				'_options_dfw_page_title_header_tag'                  => 'field_563fae5bf49d7',
				'options_dfw_page_title_header_id'                    => 'page__id-%POSTID%',
				'_options_dfw_page_title_header_id'                   => 'field_563faeb4f49d8',
				'options_dfw_page_title_header_class'                 => 'page__header',
				'_options_dfw_page_title_header_class'                => 'field_563faf5df49d9',
				'options_dfw__page_title_header_attr'                 => 'aria-labelledby="heading__id-%POSTID%" role="article"',
				'_options_dfw__page_title_header_attr'                => 'field_563fafeff49da',
				'options_dfw_page_title_heading_tag'                  => 'h1',
				'_options_dfw_page_title_heading_tag'                 => 'field_563fb057f49db',
				'options_dfw_page_title_heading_id'                   => 'heading__id-%POSTID%',
				'_options_dfw_page_title_heading_id'                  => 'field_563fb05ff49dc',
				'options_dfw_page_title_heading_class'                => 'archive__heading',
				'_options_dfw_page_title_heading_class'               => 'field_563fb067f49dd',
				'options_dfw_page_title_heading_attr'                 => 'test="attr"',
				'_options_dfw_page_title_heading_attr'                => 'field_563fb06df49de',
				'options__page_title_has_link'                        => '1',
				'_options__page_title_has_link'                       => 'field_563fb42df49e0',
				'options_dfw_page_title_link_id'                      => 'heading__link-id-%POSTID%',
				'_options_dfw_page_title_link_id'                     => 'field_563fb433f49e1',
				'options_dfw_page_title_link_class'                   => 'heading__link-class',
				'_options_dfw_page_title_link_class'                  => 'field_563fb437f49e2',
				'options_dfw_page_title_link_attr'                    => 'rel="bookmark"',
				'_options_dfw_page_title_link_attr'                   => 'field_563fb43bf49e3',
				'options_dfw_page_title_link_url'                     => '%PERMALINK%',
				'_options_dfw_page_title_link_url'                    => 'field_563fb43ff49e4',
				'options_dfw_page_title_header_attr'                  => 'aria-labelledby="heading__id-%POSTID%" role="article"',
				'_options_dfw_page_title_header_attr'                 => 'field_563fafeff49da',
				'options_dfw_page_title_has_link'                     => '0',
				'_options_dfw_page_title_has_link'                    => 'field_563fb42df49e0',
				// Entry Title
				'options_dfw__entry_title_header_tag'                 => 'header',
				'_options_dfw__entry_title_header_tag'                => 'field_563fbf617e3b2',
				'options_dfw_entry_title_header_id'                   => 'entry__id-%POSTID%',
				'_options_dfw_entry_title_header_id'                  => 'field_563fbf647e3b3',
				'options_dfw_entry_title_header_class'                => 'entry__header',
				'_options_dfw_entry_title_header_class'               => 'field_563fbf677e3b4',
				'options_dfw_entry_title_header_attr'                 => 'aria-labelledby="heading__id-%POSTID%" role="article"',
				'_options_dfw_entry_title_header_attr'                => 'field_563fbf6a7e3b5',
				'options_dfw_entry_title_heading_tag'                 => 'h1',
				'_options_dfw_entry_title_heading_tag'                => 'field_563fbf6e7e3b6',
				'options_dfw_entry_title_heading_id'                  => 'heading__id-%POSTID%',
				'_options_dfw_entry_title_heading_id'                 => 'field_563fbf717e3b7',
				'options_dfw_entry_title_heading_class'               => 'entry__heading',
				'_options_dfw_entry_title_heading_class'              => 'field_563fbf747e3b8',
				'options_dfw_entry_title_heading_attr'                => '',
				'_options_dfw_entry_title_heading_attr'               => 'field_563fbf787e3b9',
				'options_dfw_entry_title_has_link'                    => '1',
				'_options_dfw_entry_title_has_link'                   => 'field_563fc1027e3bf',
				'options_dfw_entry_title_link_id'                     => 'heading__link-id-%POSTID%',
				'_options_dfw_entry_title_link_id'                    => 'field_563fbf827e3bb',
				'options_dfw_entry_title_link_class'                  => 'heading__link-class',
				'_options_dfw_entry_title_link_class'                 => 'field_563fbf867e3bc',
				'options_dfw_entry_title_link_attr'                   => 'rel="bookmark"',
				'_options_dfw_entry_title_link_attr'                  => 'field_563fbf8a7e3bd',
				'options_dfw_entry_title_link_url'                    => '%PERMALINK%',
				'_options_dfw_entry_title_link_url'                   => 'field_563fbf8d7e3be',
				'options_dfw_add_mime_types_0_dfw_mimes_extention'    => 'svg',
				// Pagination
				'options_dfw_pagi_pagi_type'                          => 'default',
				'_options_dfw_pagi_pagi_type'                         => 'field_564bc69da69df',
				'options_dfw_pagi_wrapper_tag'                        => 'nav',
				'_options_dfw_pagi_wrapper_tag'                       => 'field_564bc802a69e0',
				'options_dfw_pagi_wrapper_id'                         => '',
				'_options_dfw_pagi_wrapper_id'                        => 'field_564bc808a69e1',
				'options_dfw_pagi_wrapper_class'                      => '',
				'_options_dfw_pagi_wrapper_class'                     => 'field_564bd0d3a69e8',
				'options_dfw_pagi_wrapper_attr'                       => 'role="navigation"',
				'_options_dfw_pagi_wrapper_attr'                      => 'field_564bc81ca69e3',
				'options_dfw_pagi_prev_text'                          => 'Previous',
				'_options_dfw_pagi_prev_text'                         => 'field_564bcca4a69e4',
				'options_dfw_pagi_next_text'                          => 'Next',
				'_options_dfw_pagi_next_text'                         => 'field_564bcea2a69e5',
				'options_dfw_pagi_sep'                                => '-',
				'_options_dfw_pagi_sep'                               => 'field_564bcf31a69e6',
				// Add Mime
				'_options_dfw_add_mime_types_0_dfw_mimes_extention'   => 'field_5642376b10841',
				'options_dfw_add_mime_types_0_dfw_mimes_mime_type'    => 'image/svg+xml',
				'_options_dfw_add_mime_types_0_dfw_mimes_mime_type'   => 'field_5642377f10842',
				'options_dfw_add_mime_types'                          => '1',
				'_options_dfw_add_mime_types'                         => 'field_5642375710840',
				// Videos
				'options_dfw_training_videos'                         => '11',
				'_options_dfw_training_videos'                        => 'field_5645000e832e9',
				'options_dfw_training_videos_0_dfw_tut_video_title'   => 'Logging In',
				'_options_dfw_training_videos_0_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_0_dfw_tut_video'         => 'https://vimeo.com/97291375',
				'_options_dfw_training_videos_0_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_1_dfw_tut_video_title'   => 'Exploring the Dashboard',
				'_options_dfw_training_videos_1_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_1_dfw_tut_video'         => 'https://vimeo.com/97521235',
				'_options_dfw_training_videos_1_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_2_dfw_tut_video_title'   => 'Using the WordPress Admin Bar',
				'_options_dfw_training_videos_2_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_2_dfw_tut_video'         => 'https://vimeo.com/97522247',
				'_options_dfw_training_videos_2_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_3_dfw_tut_video_title'   => 'Exploring WordPress Settings',
				'_options_dfw_training_videos_3_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_3_dfw_tut_video'         => 'https://vimeo.com/97524959',
				'_options_dfw_training_videos_3_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_4_dfw_tut_video_title'   => 'WordPress Posts vs Pages',
				'_options_dfw_training_videos_4_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_4_dfw_tut_video'         => 'https://vimeo.com/97224946',
				'_options_dfw_training_videos_4_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_5_dfw_tut_video_title'   => 'Creating WordPress Posts',
				'_options_dfw_training_videos_5_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_5_dfw_tut_video'         => 'https://vimeo.com/97523280',
				'_options_dfw_training_videos_5_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_6_dfw_tut_video_title'   => 'Adding Links',
				'_options_dfw_training_videos_6_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_6_dfw_tut_video'         => 'https://vimeo.com/97224624',
				'_options_dfw_training_videos_6_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_7_dfw_tut_video_title'   => 'Adding Images in WordPress',
				'_options_dfw_training_videos_7_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_7_dfw_tut_video'         => 'https://vimeo.com/97291453',
				'_options_dfw_training_videos_7_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_8_dfw_tut_video_title'   => 'Using the WordPress Media Library',
				'_options_dfw_training_videos_8_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_8_dfw_tut_video'         => 'https://vimeo.com/97291409',
				'_options_dfw_training_videos_8_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_9_dfw_tut_video_title'   => 'Scheduling WordPress Posts',
				'_options_dfw_training_videos_9_dfw_tut_video_title'  => 'field_5645009c02ff3',
				'options_dfw_training_videos_9_dfw_tut_video'         => 'https://vimeo.com/97224933',
				'_options_dfw_training_videos_9_dfw_tut_video'        => 'field_564500af02ff4',
				'options_dfw_training_videos_10_dfw_tut_video_title'  => 'WordPress Categories & Tags',
				'_options_dfw_training_videos_10_dfw_tut_video_title' => 'field_5645009c02ff3',
				'options_dfw_training_videos_10_dfw_tut_video'        => 'https://vimeo.com/97225018',
				'_options_dfw_training_videos_10_dfw_tut_video'       => 'field_564500af02ff4',
			);
			foreach( $optins as $key => $value ) {
			  add_option( $key, $value, null, 'no' );
			}
		} // end add_options
	}
} // end DFW_Activation
$install = new DFW_Activation();
register_activation_hook( DFW_PL_PLUGIN_FILE, array( $install, 'install' ) );