<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_56461d8b4cd10',
  'title' => 'General Settings',
  'fields' => array (
    array (
      'key' => 'field_565f129e12975',
      'label' => 'General',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_564de5cc6ef68',
      'label' => 'Change Posts Post Type',
      'name' => 'dfw_change_posts_post_type',
      'type' => 'true_false',
      'instructions' => 'Change the "Posts" post type to a different name. ',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_564de5ea6ef69',
      'label' => 'Singular Name',
      'name' => 'dfw_posts_singular_name',
      'type' => 'text',
      'instructions' => 'The singular name.',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564de5cc6ef68',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564de62c6ef6a',
      'label' => 'Plural Name',
      'name' => 'dfw_posts_plural_name',
      'type' => 'text',
      'instructions' => 'The plural name.',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564de5cc6ef68',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_565faff0c075b',
      'label' => 'Remove Default Taxonomies',
      'name' => 'dfw_remove_default_taxes',
      'type' => 'true_false',
      'instructions' => 'Remove the default taxonomies for post.',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564de5cc6ef68',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_56461dade7d76',
      'label' => 'CSS',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_56461dbce7d77',
      'label' => 'Custom CSS',
      'name' => 'dfw_general_custom_css',
      'type' => 'code',
      'instructions' => 'Add custom CSS.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'language' => 'css',
      'theme' => 'monokai',
    ),
    array (
      'key' => 'field_56462a5108850',
      'label' => 'Remote CSS',
      'name' => 'dfw_general_remote_css',
      'type' => 'repeater',
      'instructions' => 'For loading remote CSS stylesheets.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => 'field_56462b1a08852',
      'min' => '',
      'max' => '',
      'layout' => 'row',
      'button_label' => 'Add Remote CSS',
      'sub_fields' => array (
        array (
          'key' => 'field_56462acd08851',
          'label' => 'Handle',
          'name' => 'dfw_general_remote_css_handle',
          'type' => 'text',
          'instructions' => 'The CSS file handle.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_56462b1a08852',
          'label' => 'URL',
          'name' => 'dfw_general_remote_css_url',
          'type' => 'text',
          'instructions' => 'URL to the stylesheet.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_56467ad9224e0',
          'label' => 'Dependencies',
          'name' => 'dfw_general_remote_css_depend',
          'type' => 'text',
          'instructions' => 'Separate by a comma ',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_56462b7c08854',
          'label' => 'Version',
          'name' => 'dfw_general_remote_css_version',
          'type' => 'text',
          'instructions' => 'The stylesheet version.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_56462bed08856',
          'label' => 'Media',
          'name' => 'dfw_general_remote_css_media',
          'type' => 'text',
          'instructions' => 'The media type.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => 'all',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
      ),
    ),
    array (
      'key' => 'field_56461dd7e7d78',
      'label' => 'JavaScript',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_56461de9e7d79',
      'label' => 'Header JavaScript',
      'name' => 'dfw_general_header_javascript',
      'type' => 'code',
      'instructions' => 'Enter JavaScript that is to placed in the header.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'language' => 'javascript',
      'theme' => 'monokai',
    ),
    array (
      'key' => 'field_56461e0be7d7a',
      'label' => 'Footer JavaScript',
      'name' => 'dfw_general_footer_javascript',
      'type' => 'code',
      'instructions' => 'Enter JavaScript that is to placed in the footer.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'language' => 'javascript',
      'theme' => 'monokai',
    ),
    array (
      'key' => 'field_5647517dc6c98',
      'label' => 'Remote JS',
      'name' => 'dfw_general_remote_js',
      'type' => 'repeater',
      'instructions' => 'For loading remote JavaScript scripts.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => '',
      'layout' => 'row',
      'button_label' => 'Add Remote JavaScript',
      'sub_fields' => array (
        array (
          'key' => 'field_5647517dc6c99',
          'label' => 'Handle',
          'name' => 'dfw_general_remote_js_handle',
          'type' => 'text',
          'instructions' => 'The JavaScript file handle.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_5647517dc6c9a',
          'label' => 'URL',
          'name' => 'dfw_general_remote_js_url',
          'type' => 'text',
          'instructions' => 'URL to the script.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_5647517dc6c9b',
          'label' => 'Dependencies',
          'name' => 'dfw_general_remote_js_depend',
          'type' => 'text',
          'instructions' => 'Separate by a comma ',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_5647517dc6c9c',
          'label' => 'Version',
          'name' => 'dfw_general_remote_js_version',
          'type' => 'text',
          'instructions' => 'The script version.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_5647517dc6c9d',
          'label' => 'In Footer',
          'name' => 'dfw_general_remote_js_footer',
          'type' => 'true_false',
          'instructions' => 'Check if JavaScript is in footer.',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'message' => '',
          'default_value' => 1,
        ),
      ),
    ),
    array (
      'key' => 'field_565ef5ca19774',
      'label' => 'Media',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_565ef5d919775',
      'label' => 'Add Mime Types',
      'name' => 'dfw_add_mime_types',
      'type' => 'repeater',
      'instructions' => 'Add Additional Mime types to allowed upload list.',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => '',
      'layout' => 'table',
      'button_label' => 'Add Mime Type',
      'sub_fields' => array (
        array (
          'key' => 'field_565ef5e919776',
          'label' => 'Mime Type',
          'name' => 'dfw_mime_type',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_565ef5f919777',
          'label' => 'Extension',
          'name' => 'dfw_mime_extension',
          'type' => 'text',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-general-settings',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;