<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array (
  'key' => 'group_562ecc43949a9',
  'title' => 'Distance Framework Template Functions',
  'fields' => array (
    array (
      'key' => 'field_562eccf383097',
      'label' => 'dfw_archive_title()',
      'name' => 'dfw_archive_title',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_562ed1001052d',
      'label' => 'Header Tag',
      'name' => 'dfw_archive_title_header_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the header wrapper. <br/><strong>Default</strong>: <header>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'header',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed1a854c67',
      'label' => 'Header ID',
      'name' => 'dfw_archive_title_header_id',
      'type' => 'text',
      'instructions' => 'The ID for the header wrapper. <br/><strong>Default</strong>: archive__id-%POSTID%',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'archive__id-%POSTID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed1d354c68',
      'label' => 'Header Class',
      'name' => 'dfw_archive_title_header_class',
      'type' => 'text',
      'instructions' => 'Additional classes used for the header wrapper. <br/><strong>Default</strong>: archive_header',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'archive__header',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed45fba658',
      'label' => 'Header Attributes',
      'name' => 'dfw_archive_title_header_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: aria-labelledby="section-heading-archive" role="article"',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'aria-labelledby="section-heading-archive" role="article"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed49cba659',
      'label' => 'Heading Tag',
      'name' => 'dfw_archive_title_heading_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the heading wrapper. <br/><strong>Default</strong>: <h1>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'h1',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed4c6ba65a',
      'label' => 'Heading ID',
      'name' => 'dfw_archive_title_heading_id',
      'type' => 'text',
      'instructions' => 'The ID for the heading wrapper. <br/><strong>Default</strong>: archive_heading',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'section-heading-archive',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed4f6ba65b',
      'label' => 'Heading class',
      'name' => 'dfw_archive_title_heading_class',
      'type' => 'text',
      'instructions' => 'Additinal classes used for the heading wrapper. <br/><strong>Default</strong>: archive__heading',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'archive__heading',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed517ba65c',
      'label' => 'Heading Attributes',
      'name' => 'dfw_archive_title_heading_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed543ba65d',
      'label' => 'Archives Title',
      'name' => 'dfw_archive_title_archives_title',
      'type' => 'text',
      'instructions' => 'The text preceding the archives type. <br/><strong>Default</strong>: Archives:',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Archives:',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed56dba65e',
      'label' => 'Category Title',
      'name' => 'dfw_archive_title_category_title',
      'type' => 'text',
      'instructions' => 'The text preceding the category type. <br/><strong>Default</strong>: Category:',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Category:',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed620ba65f',
      'label' => 'Tag Title',
      'name' => 'dfw_archive_title_tag_title',
      'type' => 'text',
      'instructions' => 'The text preceding the tag type. <br/><strong>Default</strong>: Tag:',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Tag:',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed63dba660',
      'label' => 'Author Title',
      'name' => 'dfw_archive_title_author_title',
      'type' => 'text',
      'instructions' => 'The text preceding the author type. <br/><strong>Default</strong>: Author:',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Author:',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56378ee348933',
      'label' => 'Author Display Name',
      'name' => 'dfw_archive_title_author_display',
      'type' => 'select',
      'instructions' => 'Select how the author\'s name is to be displayed. <br/><strong>Default</strong>: Username',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'username' => 'Username',
        'display_name' => 'Display Name',
        'nicename' => 'Nicename',
        'first_last' => 'First and Last Name',
        'custom' => 'Custom',
      ),
      'default_value' => array (
        'username' => 'username',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_56379037b0d83',
      'label' => 'Custom Author Name',
      'name' => 'dfw_archive_title_author_custom',
      'type' => 'text',
      'instructions' => 'Use the template tags to create a custom author display name. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_56378ee348933',
            'operator' => '==',
            'value' => 'custom',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed6fc19dc8',
      'label' => 'Year Title',
      'name' => 'dfw_archive_title_year_title',
      'type' => 'text',
      'instructions' => 'The text preceding the year type. <br/><strong>Default</strong>: Year:',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Year:',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed72919dc9',
      'label' => 'Year Display Format',
      'name' => 'dfw_archive_title_year_format',
      'type' => 'text',
      'instructions' => 'The display format of the year. <a href="http://php.net/manual/en/datetime.formats.date.php">Date Formats</a><br/><strong>Default</strong>: Y',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Y',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed74a19dca',
      'label' => 'Month Title',
      'name' => 'dfw_archive_title_month_title',
      'type' => 'text',
      'instructions' => 'The text preceding the month type. <br/><strong>Default</strong>: Month:',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Month:',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed76f19dcb',
      'label' => 'Month Display Format',
      'name' => 'month_display_format',
      'type' => 'text',
      'instructions' => 'The display format of the month. <a href="http://php.net/manual/en/datetime.formats.date.php">Date Formats</a><br/><strong>Default</strong>: F Y',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'F Y',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed79119dcc',
      'label' => 'Day Title',
      'name' => 'dfw_archive_title_day_title',
      'type' => 'text',
      'instructions' => 'The text preceding the day type. <br/><strong>Default</strong>: Day:',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Day:',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed7c119dcd',
      'label' => 'Day Display Format',
      'name' => 'dfw_archive_title_day_format',
      'type' => 'text',
      'instructions' => 'The display format of the day. <a href="http://php.net/manual/en/datetime.formats.date.php">Date Formats</a><br/><strong>Default</strong>: F j, Y',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'F j, Y',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed7f1081eb',
      'label' => 'dfw_custom_excerpt()',
      'name' => 'dfw_custom_excerpt',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_5637769784719',
      'label' => 'Preserve Content Markup',
      'name' => 'dfw_custom_excerpt_preserve',
      'type' => 'true_false',
      'instructions' => 'Preserve the HTML markup of the entry. <br/><strong>Default</strong>: true',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 1,
    ),
    array (
      'key' => 'field_563776f78471a',
      'label' => 'Wrapper Tag',
      'name' => 'dfw_custom_excerpt_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag to wrap the excerpt in. <br/><strong>Default</strong>: p',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_5637769784719',
            'operator' => '!=',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'p',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed8ad20f6e',
      'label' => 'The Content',
      'name' => 'dfw_custom_excerpt_content',
      'type' => 'text',
      'instructions' => 'The content used for the excepts. <br/><strong>Default</strong>: %CONTENT%',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '%CONTENT%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56376d8c540be',
      'label' => 'Count By',
      'name' => 'dfw_custom_excerpt_type',
      'type' => 'select',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => 'all-options',
        'id' => '',
      ),
      'choices' => array (
        'word' => 'Count by Word',
        'letter' => 'Count by Letter',
      ),
      'default_value' => array (
        'word' => 'word',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_562ed8e320f6f',
      'label' => 'Excerpt Length',
      'name' => 'dfw_custom_excerpt_length',
      'type' => 'text',
      'instructions' => 'The amount of words or letter to show in the excerpt. <br/><strong>Default</strong>: 30',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 30,
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ed90520f70',
      'label' => 'Has Ellipsis',
      'name' => 'dfw_custom_excerpt_has_ellipsis',
      'type' => 'true_false',
      'instructions' => 'Check this if you want to include an ellipsis.<br/><strong>Default</strong>: true',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_562ed92b20f71',
      'label' => 'Ellipsis',
      'name' => 'dfw_custom_excerpt_ellipsis',
      'type' => 'text',
      'instructions' => 'The ellipsis show at the end of the excerpt. <br/><strong>Default</strong>: ...',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_562ed90520f70',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '...',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562edf22c9f59',
      'label' => 'Ellipsis Link',
      'name' => 'dfw_custom_excerpt_ellipsis_link',
      'type' => 'true_false',
      'instructions' => 'Check this if you want to the ellipsis to be a link.<br/><strong>Default</strong>: true',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_562ed90520f70',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_562edffcc9f5a',
      'label' => 'Ellipsis ID',
      'name' => 'dfw_custom_excerpt_ellipsis_id',
      'type' => 'text',
      'instructions' => 'The ID for the ellipsis. <br/><strong>Default</strong>: ellipsis__id-%POSTID%',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_562ed90520f70',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'ellipsis__id-%POSTID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ee0ccc9f5b',
      'label' => 'Ellipsis Class',
      'name' => 'dfw_custom_excerpt_ellipsis_class',
      'type' => 'text',
      'instructions' => 'Classes for the ellipsis. <br/><strong>Default</strong>: ellipsis__class',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_562ed90520f70',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'ellipsis__class',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_562ee170c9f5c',
      'label' => 'Ellipsis Attributes',
      'name' => 'dfw_custom_excerpt_ellipsis_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: rel="bookmark"',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_562ed90520f70',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'rel="bookmark"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56376728254eb',
      'label' => 'Has Link',
      'name' => 'dfw_custom_excerpt_has_link',
      'type' => 'true_false',
      'instructions' => 'Check this if you want to include an link.<br/><strong>Default</strong>: false',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_56376899254ec',
      'label' => 'Link Text',
      'name' => 'dfw_custom_excerpt_link_text',
      'type' => 'text',
      'instructions' => 'The text used for the link. <br/><strong>Default</strong>: <em>More</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_56376728254eb',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'More',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563768eb254ed',
      'label' => 'Link ID',
      'name' => 'dfw_custom_excerpt_link_id',
      'type' => 'text',
      'instructions' => 'The ID for the link. <br/><strong>Default</strong>: ellipsis__link-id-%POSTID%',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_56376728254eb',
            'operator' => '==',
            'value' => '1',
          ),
        ),
        array (
          array (
            'field' => 'field_562edf22c9f59',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'ellipsis__link-id-%POSTID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_5637692f254ee',
      'label' => 'Link Class',
      'name' => 'dfw_custom_excerpt_link_class',
      'type' => 'text',
      'instructions' => 'Classes for the link. <br/><strong>Default</strong>: ellipsis__link-class',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_56376728254eb',
            'operator' => '==',
            'value' => '1',
          ),
        ),
        array (
          array (
            'field' => 'field_562edf22c9f59',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'ellipsis__link-class',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56376a0f254ef',
      'label' => 'Link Attributes',
      'name' => 'dfw_custom_excerpt_link_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: rel="bookmark"',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_56376728254eb',
            'operator' => '==',
            'value' => '1',
          ),
        ),
        array (
          array (
            'field' => 'field_562edf22c9f59',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'rel="bookmark"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_56376a82254f0',
      'label' => 'URL',
      'name' => 'dfw_custom_excerpt_link_url',
      'type' => 'text',
      'instructions' => 'The URL to use for the excerpt. <br/><strong>Default</strong>: %PERMALINK%',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_56376728254eb',
            'operator' => '==',
            'value' => '1',
          ),
        ),
        array (
          array (
            'field' => 'field_562edf22c9f59',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '%PERMALINK%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fc3f2ac9ef',
      'label' => 'dfw_entry_title()',
      'name' => 'dfw_entry_title',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_563fbf617e3b2',
      'label' => 'Header Tag',
      'name' => 'dfw__entry_title_header_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the header wrapper. <br/><strong>Default</strong>: header',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'header',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fbf647e3b3',
      'label' => 'Header ID',
      'name' => 'dfw_entry_title_header_id',
      'type' => 'text',
      'instructions' => 'The ID for the header wrapper. <br/><strong>Default</strong>: entry__id-%POSTID%',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'entry__header',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fbf6a7e3b5',
      'label' => 'Header Attributes',
      'name' => 'dfw_entry_title_header_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: aria-labelledby="heading__id-%POSTID%" role="article"',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'aria-labelledby="heading__id-%POSTID%" role="article"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fbf6e7e3b6',
      'label' => 'Heading Tag',
      'name' => 'dfw_entry_title_heading_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the heading wrapper. <br/><strong>Default</strong>: h1',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'h1',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fbf717e3b7',
      'label' => 'Heading ID',
      'name' => 'dfw_entry_title_heading_id',
      'type' => 'text',
      'instructions' => 'The ID for the heading wrapper. <br/><strong>Default</strong>: heading__id-%POSTID%',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'heading__id-%POSTID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fbf747e3b8',
      'label' => 'Heading class',
      'name' => 'dfw_entry_title_heading_class',
      'type' => 'text',
      'instructions' => 'Additinal classes used for the heading wrapper. <br/><strong>Default</strong>: entry__heading',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'entry__heading',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fc1027e3bf',
      'label' => 'Has Link',
      'name' => 'dfw_entry_title_has_link',
      'type' => 'true_false',
      'instructions' => 'Check this if you want to include an link.<br/><strong>Default</strong>: true',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 1,
    ),
    array (
      'key' => 'field_563fbf827e3bb',
      'label' => 'Link ID',
      'name' => 'dfw_entry_title_link_id',
      'type' => 'text',
      'instructions' => 'The ID for the link. <br/><strong>Default</strong>: heading__link-id-%POSTID%',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563fc1027e3bf',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'heading__link-id-%POSTID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fbf867e3bc',
      'label' => 'Link Class',
      'name' => 'dfw_entry_title_link_class',
      'type' => 'text',
      'instructions' => 'Classes for the link. <br/><strong>Default</strong>: heading__link-class',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563fc1027e3bf',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'heading__link-class',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fbf8a7e3bd',
      'label' => 'Link Attributes',
      'name' => 'dfw_entry_title_link_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: rel="bookmark"',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563fc1027e3bf',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'rel="bookmark"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fbf8d7e3be',
      'label' => 'URL',
      'name' => 'dfw_entry_title_link_url',
      'type' => 'text',
      'instructions' => 'The URL to use for the excerpt. <br/><strong>Default</strong>: %PERMALINK%',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563fc1027e3bf',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '%PERMALINK%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d28028f9a3',
      'label' => 'dfw_display_author()',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_563fbf677e3b4',
      'label' => 'Header Class',
      'name' => 'dfw_entry_title_header_class',
      'type' => 'text',
      'instructions' => 'Additional classes used for the header wrapper. <br/><strong>Default</strong>: entry__header',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'entry__header',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fbf787e3b9',
      'label' => 'Heading Attributes',
      'name' => 'dfw_entry_title_heading_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d28de07370',
      'label' => 'Wrapper Tag',
      'name' => 'dfw_display_author_wrapper',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the author wrapper. <br/><strong>Default</strong>: span',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'span',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d29e807371',
      'label' => 'Wrapper ID',
      'name' => 'dfw_display_author_wrapper_id',
      'type' => 'text',
      'instructions' => 'The ID for the author wrapper. <br/><strong>Default</strong>: author__id-%AUTHORID%',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'author__id-%AUTHORID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d2a6707372',
      'label' => 'Wrapper Class',
      'name' => 'dfw_display_author_wrapper_class',
      'type' => 'text',
      'instructions' => 'Classes for the wrapper. <br/><strong>Default</strong>: author vcard',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'author vcard',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d2b6f72c42',
      'label' => 'Wrapper Attributes',
      'name' => 'dfw_display_author_wrapper_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: rel="author"',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'rel="author"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d2c1772c43',
      'label' => 'By text',
      'name' => 'dfw_display_author_author_text',
      'type' => 'text',
      'instructions' => 'The text preceding the author\'s name. <br/><strong>Default</strong>: By:',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'By:',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d2cb672c44',
      'label' => 'Author Display Name',
      'name' => 'dfw_display_author_author_display',
      'type' => 'select',
      'instructions' => 'Select how the author\'s name is to be displayed. <br/><strong>Default</strong>: Username',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'username' => 'Username',
        'display_name' => 'Display Name',
        'nicename' => 'Nicename',
        'first_last' => 'First and Last Name',
        'custom' => 'Custom',
      ),
      'default_value' => array (
        'username' => 'username',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_563d2ce772c45',
      'label' => 'Custom Author Name',
      'name' => 'dfw_display_author_author_custom',
      'type' => 'text',
      'instructions' => 'Use the template tags to create a custom author display name. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563d2cb672c44',
            'operator' => '==',
            'value' => 'custom',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d2dab72c46',
      'label' => 'Has Link',
      'name' => 'dfw_display_author_has_link',
      'type' => 'true_false',
      'instructions' => 'Check this if you want to include an link.<br/><strong>Default</strong>: false',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_563d2de572c47',
      'label' => 'Link ID',
      'name' => 'dfw_display_author_link_id',
      'type' => 'text',
      'instructions' => 'The ID for the link. <br/><strong>Default</strong>: author__link-id-%AUTHORID%',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563d2dab72c46',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'author__link-id-%AUTHORID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d2dec72c48',
      'label' => 'Link Class',
      'name' => 'dfw_display_author_link_class',
      'type' => 'text',
      'instructions' => 'Classes for the link. <br/><strong>Default</strong>: url fn n',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563d2dab72c46',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'url fn n',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563d2df472c49',
      'label' => 'Link Attibutes',
      'name' => 'dfw_display_author_link_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: rel="bookmark"',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563d2dab72c46',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'rel="bookmark"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563e09eae71a2',
      'label' => 'dfw_list_terms()',
      'name' => 'dfw_list_terms',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_563e0a03e71a3',
      'label' => 'Wrapper Tag',
      'name' => 'dfw_list_terms_wrapper',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the term list wrapper. <br/><strong>Default</strong>: div',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'div',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563e0a09e71a4',
      'label' => 'Wrapper ID',
      'name' => 'dfw_list_terms_wrapper_id',
      'type' => 'text',
      'instructions' => 'The ID for the term list wrapper. <br/><strong>Default</strong>: author__id-%AUTHORID%',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'author__id-%AUTHORID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563e0a0de71a5',
      'label' => 'Wrapper Class',
      'name' => 'dfw_list_terms_wrapper_class',
      'type' => 'text',
      'instructions' => 'Classes for the list terms wrapper. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563e0a14e71a6',
      'label' => 'Wrapper Attributes',
      'name' => 'dfw_list_terms_wrapper_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563f5f254d051',
      'label' => 'Terms Text',
      'name' => 'dfw_list_terms_text',
      'type' => 'text',
      'instructions' => 'The used before the term list. <br/><strong>Default</strong>: Listed In:',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Listed In:',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563f54541bd56',
      'label' => 'Taxonomy Type',
      'name' => 'dfw_list_terms_tax_type',
      'type' => 'select',
      'instructions' => 'Select the type of taconomy. <br/><strong>Default</strong>: All',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'all' => 'All Taxonomies',
        'custom' => 'A Custom List',
      ),
      'default_value' => array (
        'all' => 'all',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_563f54c51bd57',
      'label' => 'Taxonomy List',
      'name' => 'dfw_list_terms_tax_list',
      'type' => 'text',
      'instructions' => 'Separate each taxonomy slug by a space. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563f54541bd56',
            'operator' => '==',
            'value' => 'custom',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563f56221bd59',
      'label' => 'Term Class',
      'name' => 'dfw_list_terms_term_class',
      'type' => 'text',
      'instructions' => 'Classes for the terms. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563f56271bd5a',
      'label' => 'Terms Attributes',
      'name' => 'dfw_list_terms_term_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563f56f81bd5b',
      'label' => 'Has Link',
      'name' => 'dfw_list_terms_has_link',
      'type' => 'true_false',
      'instructions' => 'Check this if you want to include an link.<br/><strong>Default</strong>: true',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 1,
    ),
    array (
      'key' => 'field_563f57101bd5c',
      'label' => 'Link Class',
      'name' => 'dfw_list_terms_link_class',
      'type' => 'text',
      'instructions' => 'Classes for the link. <br/><strong>Default</strong>:<em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563f56f81bd5b',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563f57161bd5d',
      'label' => 'Link Attributes',
      'name' => 'dfw_list_terms_link_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: rel="bookmark"',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563f56f81bd5b',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'rel="bookmark"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563f5bf41bd5e',
      'label' => 'Term List Style',
      'name' => 'dfw_list_terms_list_style',
      'type' => 'select',
      'instructions' => 'Choose the style of the term list output. <br/><strong>Default</strong>: Default',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'default' => 'Default',
        'human' => 'Human List',
      ),
      'default_value' => array (
        'default' => 'default',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_563f5c631bd5f',
      'label' => 'Delimer',
      'name' => 'dfw_list_terms_list_delimer',
      'type' => 'text',
      'instructions' => 'The character to seperate the term items. <br/><strong>Default</strong>: ,',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => ',',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563f5d0f1bd60',
      'label' => 'Conjunction',
      'name' => 'dfw_list_terms_list_con',
      'type' => 'text',
      'instructions' => 'The conjunction to use before the last term item. <br/><strong>Default</strong>: and',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563f5bf41bd5e',
            'operator' => '==',
            'value' => 'human',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'and',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fadbcf49d6',
      'label' => 'dfw_page_title()',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_563fae5bf49d7',
      'label' => 'Header Tag',
      'name' => 'dfw_page_title_header_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the header wrapper. <br/><strong>Default</strong>: header',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'header',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563faeb4f49d8',
      'label' => 'Header ID',
      'name' => 'dfw_page_title_header_id',
      'type' => 'text',
      'instructions' => 'The ID for the header wrapper. <br/><strong>Default</strong>: page__id-%POSTID%',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'page__header',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563faf5df49d9',
      'label' => 'Header Class',
      'name' => 'dfw_page_title_header_class',
      'type' => 'text',
      'instructions' => 'Additional classes used for the header wrapper. <br/><strong>Default</strong>: page__header',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'page__header',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fafeff49da',
      'label' => 'Header Attributes',
      'name' => 'dfw_page_title_header_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: aria-labelledby="heading__id-%POSTID%" role="article"',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'aria-labelledby="heading__id-%POSTID%" role="article"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fb057f49db',
      'label' => 'Heading Tag',
      'name' => 'dfw_page_title_heading_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the heading wrapper. <br/><strong>Default</strong>: h1',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'h1',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fb05ff49dc',
      'label' => 'Heading ID',
      'name' => 'dfw_page_title_heading_id',
      'type' => 'text',
      'instructions' => 'The ID for the heading wrapper. <br/><strong>Default</strong>: heading__id-%POSTID%',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'heading__id-%POSTID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fb067f49dd',
      'label' => 'Heading class',
      'name' => 'dfw_page_title_heading_class',
      'type' => 'text',
      'instructions' => 'Additinal classes used for the heading wrapper. <br/><strong>Default</strong>: page__heading',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'page__heading',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fb06df49de',
      'label' => 'Heading Attributes',
      'name' => 'dfw_page_title_heading_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fb42df49e0',
      'label' => 'Has Link',
      'name' => 'dfw_page_title_has_link',
      'type' => 'true_false',
      'instructions' => 'Check this if you want to include an link.<br/><strong>Default</strong>: false',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_563fb433f49e1',
      'label' => 'Link ID',
      'name' => 'dfw_page_title_link_id',
      'type' => 'text',
      'instructions' => 'The ID for the link. <br/><strong>Default</strong>: heading__link-id-%POSTID%',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563fb42df49e0',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'heading__link-id-%POSTID%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fb437f49e2',
      'label' => 'Link Class',
      'name' => 'dfw_page_title_link_class',
      'type' => 'text',
      'instructions' => 'Classes for the link. <br/><strong>Default</strong>: heading__link-class',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563fb42df49e0',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'heading__link-class',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fb43bf49e3',
      'label' => 'Link Attributes',
      'name' => 'dfw_page_title_link_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: rel="bookmark"',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563fb42df49e0',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'rel="bookmark"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_563fb43ff49e4',
      'label' => 'URL',
      'name' => 'dfw_page_title_link_url',
      'type' => 'text',
      'instructions' => 'The URL to use for the excerpt. <br/><strong>Default</strong>: %PERMALINK%',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_563fb42df49e0',
            'operator' => '==',
            'value' => '1',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '%PERMALINK%',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bc599a69de',
      'label' => 'dfw_pagination()',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'left',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_564bc69da69df',
      'label' => 'Pagination Type',
      'name' => 'dfw_pagi_pagi_type',
      'type' => 'select',
      'instructions' => 'The type of pagination. <br/><strong>Default</strong>: deafult',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'default' => 'Default',
        'split' => 'Split',
        'numbered' => 'Numbered',
      ),
      'default_value' => array (
        'default' => 'default',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_564bc802a69e0',
      'label' => 'Wrapper Tag',
      'name' => 'dfw_pagi_wrapper_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the pagination wrapper. <br/><strong>Default</strong>: nav',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'nav',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bc808a69e1',
      'label' => 'Wrapper ID',
      'name' => 'dfw_pagi_wrapper_id',
      'type' => 'text',
      'instructions' => 'The ID for the pagination wrapper. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd0d3a69e8',
      'label' => 'Wrapper Class',
      'name' => 'dfw_pagi_wrapper_class',
      'type' => 'text',
      'instructions' => 'Classes for the pagination wrapper. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bc81ca69e3',
      'label' => 'Wrapper Attributes',
      'name' => 'dfw_pagi_wrapper_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: role="navigation"',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'role="navigation"',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bcca4a69e4',
      'label' => 'Pervious Page Text',
      'name' => 'dfw_pagi_prev_text',
      'type' => 'text',
      'instructions' => 'The text used for the Previous page button. <br/><strong>Default</strong>: Previous',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Previous',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bcea2a69e5',
      'label' => 'Next Page Text',
      'name' => 'dfw_pagi_next_text',
      'type' => 'text',
      'instructions' => 'The text used for the Next page button. <br/><strong>Default</strong>: Next',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'Next',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bcf31a69e6',
      'label' => 'Separator',
      'name' => 'dfw_pagi_sep',
      'type' => 'text',
      'instructions' => 'The character to separate the Previous and Next text. <br/><strong>Default</strong>: -',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'default',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '-',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd022a69e7',
      'label' => 'Next Wrapper Tag',
      'name' => 'dfw_pagi_next_wrapper_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the next wrapper. <br/><strong>Default</strong>: div',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'split',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'div',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd37fa69e9',
      'label' => 'Next Wrapper ID',
      'name' => 'dfw_pagi_next_wrapper_id',
      'type' => 'text',
      'instructions' => 'The ID for the next wrapper. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'split',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd39da69ea',
      'label' => 'Next Wrapper Class',
      'name' => 'dfw_pagi_next_wrapper_class',
      'type' => 'text',
      'instructions' => 'Classes for the next wrapper. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'split',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd3a7a69eb',
      'label' => 'Next Wrapper Attributes',
      'name' => 'dfw_pagi_wrapper_attr_copy',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'split',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd47ba69ec',
      'label' => 'Previous Wrapper Tag',
      'name' => 'dfw_pagi_prev_wrapper_tag',
      'type' => 'text',
      'instructions' => 'The HTML tag used for the previous wrapper. <br/><strong>Default</strong>: div',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'split',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'div',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd482a69ed',
      'label' => 'Previous Wrapper ID',
      'name' => 'dfw_pagi_prev_wrapper_id',
      'type' => 'text',
      'instructions' => 'The ID for the previous wrapper. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'split',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd488a69ee',
      'label' => 'Previous Wrapper Class',
      'name' => 'dfw_pagi_prev_wrapper_class',
      'type' => 'text',
      'instructions' => 'Classes for the previous wrapper. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'split',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd48ca69ef',
      'label' => 'Previous Wrapper Attributes',
      'name' => 'dfw_pagi_prev_wrapper_attr',
      'type' => 'text',
      'instructions' => 'Separate attributes by a space. <br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'split',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd642a69f0',
      'label' => 'Show All',
      'name' => 'dfw_pagi_show_all',
      'type' => 'true_false',
      'instructions' => 'If set to True, then it will show all of the pages instead of a short list of the pages near the current page. <br/><strong>Default</strong>: false',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'numbered',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 0,
    ),
    array (
      'key' => 'field_564bd73e3382c',
      'label' => 'End Size',
      'name' => 'dfw_pagi_end_size',
      'type' => 'text',
      'instructions' => 'How many numbers on either the start and the end list edges. <br/><strong>Default</strong>: 1',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'numbered',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 1,
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd77e3382d',
      'label' => 'Mid Size',
      'name' => 'dfw_pagi_mid_size',
      'type' => 'text',
      'instructions' => 'How many numbers to either side of current page, but not including current page. <br/><strong>Default</strong>: 1',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'numbered',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 1,
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564bd7ea3382e',
      'label' => 'Previous and Next Buttoms',
      'name' => 'dfw_pagi_prev_next',
      'type' => 'true_false',
      'instructions' => 'Whether to include the previous and next links in the list or not. <br/><strong>Default</strong>: true',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'numbered',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'message' => '',
      'default_value' => 1,
    ),
    array (
      'key' => 'field_564bd89e3382f',
      'label' => 'Type of Output',
      'name' => 'dfw_pagi_type',
      'type' => 'select',
      'instructions' => 'Controls format of the returned value. Possible values are:< br/>
• <strong>plain</strong> - A string with the links separated by a newline character.< br/>
• <strong>array</strong> - An array of the paginated link list to offer full control of display.< br/>
• <strong>list</strong> - Unordered HTML list.
<br/><strong>Default</strong>: list',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'numbered',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'choices' => array (
        'list' => 'List',
        'plain' => 'Plain',
        'array' => 'Array',
      ),
      'default_value' => array (
        'list' => 'list',
      ),
      'allow_null' => 0,
      'multiple' => 0,
      'ui' => 0,
      'ajax' => 0,
      'placeholder' => '',
      'disabled' => 0,
      'readonly' => 0,
    ),
    array (
      'key' => 'field_564c80a075fc6',
      'label' => 'Add Args',
      'name' => 'dfw_pagi_add_args',
      'type' => 'text',
      'instructions' => 'An array of query args to add.<br/><strong>Default</strong>: false',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'numbered',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => 'false',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564c812775fc7',
      'label' => 'Add Fragment',
      'name' => 'dwf__pagi_add_fragment',
      'type' => 'text',
      'instructions' => 'A string to append to each link.<br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'numbered',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564c81b275fc8',
      'label' => 'Before Page Number',
      'name' => 'dfw_pagi_before_page_number',
      'type' => 'text',
      'instructions' => 'A string to appear before the page number.<br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'numbered',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
    array (
      'key' => 'field_564c81f475fc9',
      'label' => 'After Page Number',
      'name' => 'dfw_pagi_after_page_number',
      'type' => 'text',
      'instructions' => 'A string to append after the page number.<br/><strong>Default</strong>: <em>none</em>',
      'required' => 0,
      'conditional_logic' => array (
        array (
          array (
            'field' => 'field_564bc69da69df',
            'operator' => '==',
            'value' => 'numbered',
          ),
        ),
      ),
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'default_value' => '',
      'placeholder' => '',
      'prepend' => '',
      'append' => '',
      'maxlength' => '',
      'readonly' => 0,
      'disabled' => 0,
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'acf-options-template-functions',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));

endif;